### ISSUE TITLE
Unable to create, load or update global cache file

### ISSUE THREAD

**Issue by TuneFish41** [svalabs/check_mk_automated_downtimes#2]
Hi

I am facing a few issues with the extension where I cannot consistently create, load or update the global cache file.

Symptoms:
1. The automated downtime service is flapping between Unknown and OK state. While in the OK state I get the message "Can't load cache, being updated elsewhere?". Seems like the check is flapping every check interval.
2. Contrary to what is described in the wiki, I cannot simply delete the global cache file and it is automatically renewed.
3. Also, data is only written to the global cache file in the very first `MAX_CACHE_AGE_MINUTES`. After the first 60 minutes have elapsed (default), the mechanism no longer works.

One way to get the extension running again is to restart the whole monitoring site (cmk -R).

Please let me know if I can provide you with specific information.

Unfortunately, I haven't been able to find a solution myself yet. I have already tried various things, but unfortunately I am quite inexperienced with caching, `pickle` and `fcntl`. 

If I find the time, I'll be happy to debug the code further. 

- Checkmk 2.2.0p30 CEE
- No distributed setup
- auto_downtimes Extension v2.0.0

My rule looks like this:
![grafik](https://github.com/user-attachments/assets/84affa18-3964-473d-86e2-be0e1e7546c9)

And I let the extension connect to:
- localhost
- Port 5000
- No Proxy
- No SSL verification

Best regards
Marcel :)

**Comment by sva-mh** [comment]
Hi Marcel,
are you using docker?
Best regards
Micha

**Comment by TuneFish41** [comment]
Hi
no, but Hardware Appliance with Firmware v1.7.3

**Comment by sva-mh** [comment]
Hi,

I made a quick review of the code to look for some things you described and made some changes. 
See the attached MKP.  Not sure if this solves all your problems, and it is only minimally tested, so please consider 
this as an alpha-version :-)

This version should improve the problems with "unknown" and refreshing of the global cache.

[auto_downtimes-2.0.1.mkp.zip](https://github.com/user-attachments/files/16512509/auto_downtimes-2.0.1.mkp.zip)

Best regards, 
Micha

**Comment by sva-mh** [comment]
Hi Marcel,

how many instances of the plugin are configured/running? Can you try to run it on exactly one host? (so there should be no 'locked by another process' possible)

An regarding the flapping: Is the service acually flapping between states (like OK -> UNKNOWN -> OK -> ..) or is only summary-output-text changing back and fore?

One possibility for the problems could be, that the plugin is running in a timeout. 
A normal global-cache-update should look like this:
`
[2024-08-12 14:17:28.563986] Updating global-cache                                                                                                                                      [2024-08-12 14:17:28.564020] Acquiring lock /omd/sites/dev23/tmp/check_mk/auto_downtimes_cache.lock                         
[2024-08-12 14:17:28.564188] Acquired lock /omd/sites/dev23/tmp/check_mk/auto_downtimes_cache.lock                                                                                      [2024-08-12 14:17:34.354174] Updating global-cache done                                                                                                                                [2024-08-12 14:17:34.354281] Releasing lock /omd/sites/dev23/tmp/check_mk/auto_downtimes_cache.lock            
`
In my case the duration is about 6 seconds. I did not see a "Updating global-cache done"-entry in your logs,
which *may* be an indication, that the process got aborted/killed because of the CheckMK-Service-Check-Timeout (
default 60s.) Perhaps you could increase the the Service-Check-Timeout for the AutoDownTimes-Checks to 240s for testing

Best regards
Micha
